version: "3.9"

services:
  http:
    build:
      context: .
      dockerfile: http/Dockerfile
    volumes:
      - .:/opt/app/http
    container_name: http

  server:
    build:
      context: .
      dockerfile: transport/server/Dockerfile
    container_name: server
    
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      # if you wish to set up additional user accounts specific per DB or with different roles you can use the following entry point
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod