version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: transport/server/Dockerfile
    container_name: server
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    
  http:
    build:
      context: .
      dockerfile: http/Dockerfile
    container_name: http
    ports:
      - "8080:8080"
    depends_on:
      - server
    
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      # if you wish to set up additional user accounts specific per DB or with different roles you can use the following entry point
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod