// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/dog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegName  string `protobuf:"bytes,2,opt,name=reg_name,json=regName,proto3" json:"reg_name,omitempty"`
	CallName string `protobuf:"bytes,3,opt,name=call_name,json=callName,proto3" json:"call_name,omitempty"`
	Gender   string `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *Dog) Reset() {
	*x = Dog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dog) ProtoMessage() {}

func (x *Dog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dog.ProtoReflect.Descriptor instead.
func (*Dog) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{0}
}

func (x *Dog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dog) GetRegName() string {
	if x != nil {
		return x.RegName
	}
	return ""
}

func (x *Dog) GetCallName() string {
	if x != nil {
		return x.CallName
	}
	return ""
}

func (x *Dog) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type CreateDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *CreateDogRequest) Reset() {
	*x = CreateDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogRequest) ProtoMessage() {}

func (x *CreateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogRequest.ProtoReflect.Descriptor instead.
func (*CreateDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDogRequest) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type CreateDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *CreateDogResponse) Reset() {
	*x = CreateDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogResponse) ProtoMessage() {}

func (x *CreateDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogResponse.ProtoReflect.Descriptor instead.
func (*CreateDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDogResponse) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type GetDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DogId string `protobuf:"bytes,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
}

func (x *GetDogRequest) Reset() {
	*x = GetDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogRequest) ProtoMessage() {}

func (x *GetDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogRequest.ProtoReflect.Descriptor instead.
func (*GetDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{3}
}

func (x *GetDogRequest) GetDogId() string {
	if x != nil {
		return x.DogId
	}
	return ""
}

type GetDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *GetDogResponse) Reset() {
	*x = GetDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogResponse) ProtoMessage() {}

func (x *GetDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogResponse.ProtoReflect.Descriptor instead.
func (*GetDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{4}
}

func (x *GetDogResponse) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type UpdateDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *UpdateDogRequest) Reset() {
	*x = UpdateDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDogRequest) ProtoMessage() {}

func (x *UpdateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDogRequest.ProtoReflect.Descriptor instead.
func (*UpdateDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDogRequest) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type UpdateDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *UpdateDogResponse) Reset() {
	*x = UpdateDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDogResponse) ProtoMessage() {}

func (x *UpdateDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDogResponse.ProtoReflect.Descriptor instead.
func (*UpdateDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDogResponse) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type DeleteDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DogId string `protobuf:"bytes,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
}

func (x *DeleteDogRequest) Reset() {
	*x = DeleteDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDogRequest) ProtoMessage() {}

func (x *DeleteDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDogRequest.ProtoReflect.Descriptor instead.
func (*DeleteDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDogRequest) GetDogId() string {
	if x != nil {
		return x.DogId
	}
	return ""
}

type DeleteDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DogId string `protobuf:"bytes,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`
}

func (x *DeleteDogResponse) Reset() {
	*x = DeleteDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDogResponse) ProtoMessage() {}

func (x *DeleteDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDogResponse.ProtoReflect.Descriptor instead.
func (*DeleteDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDogResponse) GetDogId() string {
	if x != nil {
		return x.DogId
	}
	return ""
}

type ListDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDogRequest) Reset() {
	*x = ListDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDogRequest) ProtoMessage() {}

func (x *ListDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDogRequest.ProtoReflect.Descriptor instead.
func (*ListDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{9}
}

type ListDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *ListDogResponse) Reset() {
	*x = ListDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDogResponse) ProtoMessage() {}

func (x *ListDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDogResponse.ProtoReflect.Descriptor instead.
func (*ListDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_proto_rawDescGZIP(), []int{10}
}

func (x *ListDogResponse) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

var File_proto_dog_proto protoreflect.FileDescriptor

var file_proto_dog_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x73, 0x72, 0x63, 0x22, 0x65, 0x0a, 0x03, 0x44, 0x6f, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x65, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x65, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2e, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x2f, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x26,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x64, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x64, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67, 0x52,
	0x03, 0x64, 0x6f, 0x67, 0x22, 0x2e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67, 0x52,
	0x03, 0x64, 0x6f, 0x67, 0x22, 0x2f, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67,
	0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x67, 0x49, 0x64,
	0x22, 0x2a, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x32, 0xab, 0x02,
	0x0a, 0x0a, 0x44, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x12, 0x15, 0x2e, 0x73, 0x72, 0x63, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x44,
	0x6f, 0x67, 0x12, 0x12, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x12, 0x15, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x6f, 0x67, 0x12, 0x15, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x72,
	0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x12, 0x13,
	0x2e, 0x73, 0x72, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dog_proto_rawDescOnce sync.Once
	file_proto_dog_proto_rawDescData = file_proto_dog_proto_rawDesc
)

func file_proto_dog_proto_rawDescGZIP() []byte {
	file_proto_dog_proto_rawDescOnce.Do(func() {
		file_proto_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dog_proto_rawDescData)
	})
	return file_proto_dog_proto_rawDescData
}

var file_proto_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_dog_proto_goTypes = []interface{}{
	(*Dog)(nil),               // 0: src.Dog
	(*CreateDogRequest)(nil),  // 1: src.CreateDogRequest
	(*CreateDogResponse)(nil), // 2: src.CreateDogResponse
	(*GetDogRequest)(nil),     // 3: src.GetDogRequest
	(*GetDogResponse)(nil),    // 4: src.GetDogResponse
	(*UpdateDogRequest)(nil),  // 5: src.UpdateDogRequest
	(*UpdateDogResponse)(nil), // 6: src.UpdateDogResponse
	(*DeleteDogRequest)(nil),  // 7: src.DeleteDogRequest
	(*DeleteDogResponse)(nil), // 8: src.DeleteDogResponse
	(*ListDogRequest)(nil),    // 9: src.ListDogRequest
	(*ListDogResponse)(nil),   // 10: src.ListDogResponse
}
var file_proto_dog_proto_depIdxs = []int32{
	0,  // 0: src.CreateDogRequest.dog:type_name -> src.Dog
	0,  // 1: src.CreateDogResponse.dog:type_name -> src.Dog
	0,  // 2: src.GetDogResponse.dog:type_name -> src.Dog
	0,  // 3: src.UpdateDogRequest.dog:type_name -> src.Dog
	0,  // 4: src.UpdateDogResponse.dog:type_name -> src.Dog
	0,  // 5: src.ListDogResponse.dog:type_name -> src.Dog
	1,  // 6: src.DogService.CreateDog:input_type -> src.CreateDogRequest
	3,  // 7: src.DogService.GetDog:input_type -> src.GetDogRequest
	5,  // 8: src.DogService.UpdateDog:input_type -> src.UpdateDogRequest
	7,  // 9: src.DogService.DeleteDog:input_type -> src.DeleteDogRequest
	9,  // 10: src.DogService.ListDog:input_type -> src.ListDogRequest
	2,  // 11: src.DogService.CreateDog:output_type -> src.CreateDogResponse
	4,  // 12: src.DogService.GetDog:output_type -> src.GetDogResponse
	6,  // 13: src.DogService.UpdateDog:output_type -> src.UpdateDogResponse
	8,  // 14: src.DogService.DeleteDog:output_type -> src.DeleteDogResponse
	10, // 15: src.DogService.ListDog:output_type -> src.ListDogResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dog_proto_init() }
func file_proto_dog_proto_init() {
	if File_proto_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dog_proto_goTypes,
		DependencyIndexes: file_proto_dog_proto_depIdxs,
		MessageInfos:      file_proto_dog_proto_msgTypes,
	}.Build()
	File_proto_dog_proto = out.File
	file_proto_dog_proto_rawDesc = nil
	file_proto_dog_proto_goTypes = nil
	file_proto_dog_proto_depIdxs = nil
}
